#!/usr/bin/env python3
# -*- coding: utf-8 -*-


from src import choosing
from src import config_load



def make_choices(cfg):
    chooser = choosing.FrameChooser.fromReadData(cfg)
    chooser.plot_hist()
    choices = chooser.make_choices()
    return choices, chooser


if __name__ == '__main__':
    cfg = config_load.load_options("config.py")
    print(cfg)
    make_choices(cfg)
